# Generated by Django 5.0.6 on 2024-07-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NPCList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ['-date']},
        ),
    ]
